name: Poker
main: com.modcrafting.poker.Poker
version: 0.9
#website: 
author: Deathmarine
description: >
             Economy Based Poker Mini-Game.
commands:
  poker:
    description: Main command used to play poker.
    permission: poker.command
    usage: /<command>
permissions:
  poker.*:
    default: op
    description: Allows the Administration to Full Control
    children:
      poker.command: true
  poker.command:
    description: Allows players to play poker.